export const LOGIN_FORM_VALIDATING_USER = 'LOGIN_FORM_VALIDATING_USER';
export const LOGIN_FORM_VALIDATING_USER_SUCCESS = 'LOGIN_FORM_VALIDATING_USER_SUCCESS';
export const LOGIN_FORM_VALIDATING_USER_ERROR = 'LOGIN_FORM_VALIDATING_USER_ERROR';
export const SNACKBAR_ONCHANGE = 'SNACKBAR_ONCHANGE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOCAL_STORAGE = 'storage/localStorage';
export const SESSION_STORAGE = 'storage/sessionStorage';


